services:
  studio_site:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: studio_site
    restart: unless-stopped
    expose:
      - "8080"
    networks:
      - web

networks:
  web:
    external: true
